#!/bin/sh
# entrypoint.sh — runs at container start. Generates config.php from env vars
# if it doesn't exist yet, then hands off to php-fpm.
set -e

CONFIG_FILE="/var/www/html/config.php"

if [ ! -f "$CONFIG_FILE" ] && [ -n "$DB_NAME" ]; then
    cat > "$CONFIG_FILE" <<PHP
<?php
// Auto-generated by docker/entrypoint.sh. Safe to edit.

const DB_HOST     = '${DB_HOST:-db}';
const DB_NAME     = '${DB_NAME}';
const DB_USER     = '${DB_USER}';
const DB_PASS     = '${DB_PASS}';

const SMTP_HOST     = '${SMTP_HOST:-smtp.example.com}';
const SMTP_PORT     = ${SMTP_PORT:-587};
const SMTP_PROTOCOL = '${SMTP_PROTOCOL:-tls}';
const SMTP_USER     = '${SMTP_USER:-}';
const SMTP_PASS     = '${SMTP_PASS:-}';

const APP_NAME = 'Project Management System';
const APP_URL  = '${APP_URL:-http://localhost}';
const TIMEZONE = 'UTC';

const SESSION_LIFETIME      = 3600;
const PASSWORD_RESET_EXPIRY = 3600;
const ENCRYPTION_KEY        = '${ENCRYPTION_KEY:-please-change-this-32-char-key}';
PHP
    echo "[entrypoint] Wrote $CONFIG_FILE from environment"
fi

exec "$@"